[package]
name = "subset"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parcom = { path = "../parcom" }
cranelift = "0.78"
cranelift-jit = "0.78"
cranelift-module = "0.78"
